# Generated by Django 4.1.2 on 2022-10-22 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='coordinador',
            fields=[
                ('coor_cedula', models.IntegerField(primary_key=True, serialize=False, verbose_name='Cedula')),
                ('coor_nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('coor_apellido', models.CharField(max_length=45, verbose_name='Apellido')),
                ('coor_correo', models.CharField(max_length=30, verbose_name='Correo')),
                ('coor_telefono', models.CharField(max_length=10, verbose_name='Telefono')),
            ],
        ),
        migrations.CreateModel(
            name='docente',
            fields=[
                ('doc_cedula', models.IntegerField(primary_key=True, serialize=False, verbose_name='Cedula')),
                ('doc_nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('doc_apellido', models.CharField(max_length=45, verbose_name='Apellido')),
                ('doc_correo', models.CharField(max_length=30, verbose_name='Correo')),
                ('doc_telefono', models.CharField(max_length=10, verbose_name='Telefono')),
            ],
        ),
        migrations.CreateModel(
            name='horario',
            fields=[
                ('hor_codigo', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo Horario')),
                ('hor_fechaInicio', models.DateField(null=True, verbose_name='Fecha Inicio')),
                ('hor_fechaFin', models.DateField(null=True, verbose_name='Fecha Fin')),
                ('hor_horaInicio', models.TimeField(null=True, verbose_name='Hora Inicio')),
                ('hor_horaFin', models.TimeField(null=True, verbose_name='Hora Fin')),
                ('coor_cedula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.coordinador')),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('user_documento', models.IntegerField(primary_key=True, serialize=False, verbose_name='Cedula')),
                ('user_nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('user_apellido', models.CharField(max_length=45, verbose_name='Apellido')),
                ('user_correo', models.CharField(max_length=30, verbose_name='Correo')),
                ('user_usuario', models.CharField(max_length=30, verbose_name='Usuario')),
                ('user_clave', models.CharField(max_length=100, verbose_name='Contraseña')),
                ('user_rol', models.CharField(max_length=13, verbose_name='Rol')),
                ('coor_cedula', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.coordinador')),
            ],
        ),
        migrations.CreateModel(
            name='horariodocente',
            fields=[
                ('hordoc_codigo', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo Horario Docente')),
                ('doc_cedula', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.docente')),
                ('hor_codigo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.horario')),
            ],
        ),
    ]
